package com.example.drishtimukesh

import java.sql.Date

enum class ClassType {
    CLASS_9,CLASS_10, CLASS_11, CLASS_12
}

data class User(
    val userName: String? = null,       // User_Name
    val name: String? = null,           // Name
    val deviceId: String = "",          // device_id
    val email: String = "",             // Email
    val phone: String = "",             // Phone
    val userClass: String = "",         // Class (or Int if you want numeric class levels)
    val coins: Int = 0,                 // Coins
    val password: String = "",          // passwords
    val listOfCourses: List<Int> = emptyList(), // Array of course IDs
    val role : String = "Student"
)
data class Course(
    val courseId : String ="",// ye bs humare refference ke liye hai
    val clas : String = "",
    val price : Double = 0.0,
    val startDate : Long = 0L,
    val endDate : Long= 0L,
    val id : String ="", //primary key generated by the firebase
    val name : String ="",
    val description : String = "",
    val baseImage : List<String> = emptyList<String>(),
    val driveFolderId: String = "",      // root Drive folder for course
    val subjects: List<Subject> = emptyList()
)

data class Subject(
    val id: String = "",
    val name: String = "",
    val driveFolderId: String = "",
    val chapters: List<Chapter> = emptyList()
)

data class Chapter(
    val id: String = "",
    val name: String = "",
    val driveFolderId: String = ""
)