package com.example.drishtimukesh

import java.sql.Date

enum class ClassType {
    CLASS_9,CLASS_10, CLASS_11, CLASS_12
}

data class User(
    val userName: String? = null,       // User_Name
    val name: String? = null,           // Name
    val deviceId: String = "",          // device_id
    val email: String = "",             // Email
    val phone: String = "",             // Phone
    val userClass: String = "",         // Class (or Int if you want numeric class levels)
    val coins: Int = 0,                 // Coins
    val password: String = "",          // passwords
    val listOfCourses: List<Int> = emptyList(), // Array of course IDs
    val role : String = "Student"
)
data class Course(
    val courseId : String ="",// ye bs humare refference ke liye hai
    val clas : String = "",
    val price : Double = 0.0,
    val startDate : Long = 0L,
    val endDate : Long= 0L,
    val id : String ="", //primary key generated by the firebase
    val name : String ="",
    val description : String = "",
    val baseImage : List<String> = emptyList<String>(),
    val driveFolderId: String = "",      // root Drive folder for course
    val subjects: List<Subject> = emptyList()
)

data class Subject(
    val id: String = "",
    val name: String = "",
    val driveFolderId: String = "",
    val chapters: List<Chapter> = emptyList()
)

data class Chapter(
    val id: String = "",
    val name: String = "",
    val driveFolderId: String = ""
)


//

//// A Subject document (fetched from /courses/{courseId}/subjects/{subjectId})
//data class Subject(
//    val id: String = "",
//    val name: String = "",
//    val driveFolderId: String = ""
//
//    // NOTE: The 'chapters' list is removed because chapters are fetched from a sub-collection.
//)
//
//// A Chapter document (fetched from .../subjects/{subjectId}/chapters/{chapterId})
//data class Chapter(
//    val id: String = "",
//    val name: String = "",
//    val driveFolderId: String = ""
//
//    // NOTE: The 'lectures' list is removed because lectures should be a sub-collection.
//)
//
//// A Lecture document (MUST BE ADDED for getLecturesByChapterId)
//data class Lecture(
//    val id: String = "",
//    val name: String = "",
//    val durationMin: Int = 0,
//    val driveFileId: String = "", // Add a field to hold the specific file/video ID
//    val isCompleted: Boolean = false // Useful for tracking progress
//)
